eureka:         #tells about the Eureka server details and its refresh time
  client:
    registerWithEureka: true   #telling the server not to register himself in the service registry////////////////////
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://172.0.0.1:8761/eureka/

spring:
  application:
    name: api-service   #current service name to be used by the eureka server
