version: "3"
services:
  spring-eureka-server:
    build: ./spring-eureka-server
    network_mode: host
    restart: always
    ports:
      - 8761:8761
    expose:
      - 8761
#    depends_on:
#      -spring-config-server

  spring-api-server:
    build: ./spring-api-server
    network_mode: host
    restart: always
    ports:
      - 8085:8085
    expose:
      - 8085

  spring-track-service:
    build: ./spring-track-service
    network_mode: host
    restart: always
    ports:
      - 8088:8088
    expose:
      - 8088
#    depends_on:
#      -mongo

  spring-user-service:
    build: ./spring-user-service
    network_mode: host
    restart: always
    ports:
      - 8099:8099
    expose:
      - 8099
#    depends_on:
#      -mysql

  spring-config-server:
    build: ./spring-config-server
    network_mode: host
    restart: always
    ports:
      - 8081:8081
    expose:
      - 8081

  mongo:
    image: mongo
    ports:
      - 27017:27017
    expose:
      - 27017

  mysql:
    image: mysql:5.7
    ports:
      - 3307:3307
    expose:
      - 3307


