server:
  port: 8098    #default port where the service will be started

eureka:         #tells about the Eureka server details and its refresh time
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    registerWithEureka: true   #telling the server not to register himself in the service registry
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5

spring:
  application:
    name: User-Service   #current service name to be used by the eureka server

management:
  security:
    enabled: false  #disable the spring security on the management endpoints like /env, /refresh etc.

    datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/Userservice
      username: root
      password: Root@123

      jpa:
        database: MYSQL
        hibernate:
          ddl-auto: create-drop

logging:
  level:
    com.example.howtodoinjava: DEBUG